apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nginx.fullname" . }}-statefulset
spec:
  serviceName: "nginx"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx.labels" . | nindent 8 }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - mountPath: {{ .Values.persistence.mountPath }}
          name: nginx-storage
  volumeClaimTemplates:
  - metadata:
      name: nginx-storage
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
