apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "nginx.labels" . | nindent 4 }}
